[tool]
[tool.poetry]
name = "OlympusUserBot_Deployer"
version = "1.0"
description = "Automatic Deploy OlympusUserBot to Heroku"
authors = ["Zeus Usta"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
